version: '1'

services:
  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    env_file:
      - ./src/api/.env.development
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ./src/api:/home/node/app
