version: "3.8"
services:
    node_remote_feedback_api:
        build: 
            context: "./"
            dockerfile: Dockerfile
        volumes:
            - .:/app/
            - /app/node_modules
        environment:
            NODE_ENV: development
        volumes:
            - "./:/usr/src/app"
            - "./.env.development:/.env.development"
        ports:
            - 3000:3000

